### ISSUE TITLE
attrlen should be unsigned almost everywhere

### ISSUE THREAD

**Issue by jengelh** [thom311/libnl#124]
Google made themselves a patch to nla_reserve to check for negative `attrlen` values in `nla_reserve`, but to me that points to a deeper issue that attrlen should have been unsigned to begin with.

https://android.googlesource.com/platform/external/libnl/+/f0b40192efd1af977564ed6335d42a8bbdaf650a%5E!/

**Comment by thom311** [comment]
The patch you refer to is in a downstream fork of libnl (by android).
It is based on libnl3, commit 513e45ccce5ae286fc67fde1a1bf703e9c8d83aa, from 6 years ago.

libnl3 in general is not robust when being called with invalid arguments. Don't do that, and validate the arguments before calling libnl3 functions. It's a bug to call libnl functions with invalid/untrusted arguments, and those bugs should be fixed.

It's clear that negative values don't make sense for these length arguments, and maybe unsigned should be used. Since you are responsible to pass valid arguments, a valid signed argument is just as good as a valid unsigned one. I agree, unsigned would be more suitable, but it doesn't matter too much. And more importantly: the existing API cannot be changed at this point.

Anyway, I added a patch to check for these two cases and error out. If you find that this patch matters to you, you encountered a bug somewhere else and this merely tampers over it. If that bug is in libnl3 itself, please open an issue/pull-request.

Thanks for reporting upstream!!

**Comment by tgraf** [comment]
@jengelh Reading the CVE and the diff I cannot identify how this libnl bug by itself causes process privilege escalation. No matter what Netlink message results in the end, the kernel should reject it. Assuming this is merely process escalation then passing unverified data from an unprivileged process into libnl APIs linked to a privileged process is definitely not safe. That's a bug in usage of libnl then.
