### ISSUE TITLE
What is epollerr means for netlink sockets 

### ISSUE THREAD

**Issue by cdprashanth** [thom311/libnl#132]
Hi
Why am i getting EPOLLERR in epoll_wait() on netlink socket ? is this because other side of netlink ie kernel side closed connection ?
even if kernel side closed connection why non-stop repeated EPOLLERR s on netlink sockets ?

**Comment by thom311** [comment]
This has nothing to do with libnl3, but with epoll, netlink, and kernel behavior.

I would suspect that you get EPOLLERR because an error happened on the file descriptor.
I would suspect you get non-stop repeated EPOLLERR because you didn't retrieve the pending error state from the socket.

I am not familiar with epoll, beyond reading the manual page.
