### ISSUE TITLE
Is there a configuration option to enable installing private header files.

### ISSUE THREAD

**Issue by d0u9** [thom311/libnl#157]
I want to directly use some data struct in libnl, such as `struct nl_object`. However, these data structures are defined in private header files, which are not install defaultly to `/usr/include/libnl3`.

So, how could I instruct the installer to install theses header files when I compile it from source. Or, is there alternatives in which I can directly reference these private data structure.

**Comment by thom311** [comment]
You cannot. These structures are private because they are not part of public API. Also, their memory layout might change between versions, so that a different version of the library might be incompatible (and you get memory corruption and crashes).

Of course, for your own prupose, you can build libnl from source and do whatever you want, but that doesn't seem like a good idea, for anything serious because it would only work with your fork of the library.

If there is functionality in these that you want to extend/expose, submit a pull request with new public API.

Thanks.
