### ISSUE TITLE
Warning: unsigned conversion from ‘int’ to ‘long unsigned int’ changes value from ‘-4’ to ‘18446744073709551612’

### ISSUE THREAD

**Issue by szotsaki** [thom311/libnl#211]
Macro `NLA_HDRLEN` in `netlink.h` emits the warning above. When you compile on x64 with  `-Wsign-conversion`, you can prove it with the following program where `temp` contains the expanded version of the macro:

```c
#include <linux/netlink.h>

int main() {
    int temp = ((int) (((sizeof(struct nlattr)) + 4 - 1) & ~(4 - 1)));
    return temp;
}
```

The warning emitted is:

```
netlink.cpp: In function ‘int main()’:
netlink.cpp:4:60: warning: unsigned conversion from ‘int’ to ‘long unsigned int’ changes value from ‘-4’ to ‘18446744073709551612’ [-Wsign-conversion]
     int temp = ((int) (((sizeof(struct nlattr)) + 4 - 1) & ~(4 - 1)));
                                                            ^~~~~~~~
```

**Comment by thom311** [comment]
`NLA_HDRLEN` macro comes from `linux/netlink.h`, which is part of the user-space API of kernel.

Specifically, it comes from here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/include/uapi/linux/netlink.h?id=cd2a3bf02625ffad02a6b9f7df758ee36cf12769#n90

So, the bug is not reported at the right place nor can it be fixed here.

**Comment by szotsaki** [comment]
Ahh, I see. Sorry for the noise, and thanks for the pointer.

**Comment by thom311** [comment]
No problem. Thanks!

**Comment by hmaarrfk** [comment]
Did you ever resolve this?

**Comment by hmaarrfk** [comment]
Did you ever end up working with the right people to resolve this? Are you able to cross reference to the discussion?

**Comment by hmaarrfk** [comment]
For me I need this:
https://netdev.vger.kernel.narkive.com/vOZI4oX0/patch-netlink-fix-gcc-wconversion-compilation-warning

I guess if you aren't stuck on an 11 year old kernel it should be ok!

**Comment by thom311** [comment]
ah right: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4b8fe66300acb2fba8b16d62606e0d30204022fc

From the original report, it can also be seen that `4` is used (instead of `4U`), so the patch wasn't there.

libnl also has a copy of `netlink.h` header, but that one too defines `4U`. So I think there is nothing to do for libnl.
