### ISSUE TITLE
How to add a new qdisc

### ISSUE THREAD

**Issue by fruffy** [thom311/libnl#216]
Hello,
I would like to add the [fair queuing](http://man7.org/linux/man-pages/man8/tc-fq.8.html) qdisc to libnl, or at least develop something similar to the qdiscs in the route [folder](https://github.com/thom311/libnl/tree/master/lib/route/qdisc). However, I am unsure how to get started. Is there good resource material or templates on how add new qdiscs and what structures are required?

**Comment by thom311** [comment]
I think the manual pages from `iproute2` explain fairly well how qdisks work.

I don't know the answer to your question, but I would start creating the desired configuration with iproute2 (tc commands). Then, I would look at the source code of iproute2 and kernel which netlink messages are sent, in order to configure what you just did with iproute2. Finally, I would craft those netlink messages with libnl3 and send them.

There might be better approaches or better documentation. I will close this issue (also because I don't know how to answer it better). But further pointers are welcome, and please reopen if you think there is something to add. Thanks.

**Comment by fruffy** [comment]
Thanks, my main point of confusion was trying to understand how the data structures and function calls in route/qdisc came about. I guess mimicking iproute2 is the best bet here then.
