### ISSUE TITLE
version libnl 1 and libnl 3 symbols to prevent errors when both are linked in

### ISSUE THREAD

**Issue by ZeroChaos-** [thom311/libnl#38]
I don't really understand this stuff very well but:

When kismet links to libnl-3 and libpcap, but libpcap is linked to libnl-1, this causes segfaults.

Downstream gentoo bug offers some patches to help correct these kinds of issues which are prevalent across distributions.

https://bugs.gentoo.org/show_bug.cgi?id=469336

**Comment by thom311** [comment]
libnl3 has the patch from https://bugs.gentoo.org/show_bug.cgi?id=469336#c2 since commit 0eb665c693ab2673b722ffd75df744f75fb7e2fe .

Recently, symbol versioning was reworked further (commit b5a56254b9f9c3b74ae8bf54f468db4efb3d0978).

downstream bug also has patches for libnl-1, but visioning is not added there...
libnl-1 is quite dead now -- and this issue tracker is for libnl3.


Closing this as "fixed"

**Comment by thom311** [comment]
opened issue for libnl1: https://github.com/tgraf/libnl-1.1-stable/issues/2
