### ISSUE TITLE
--as-needed, __init and libnl3

### ISSUE THREAD

**Issue by socketpair** [thom311/libnl#93]
`gcc -I/usr/include/libnl3 minimal.c -lnl-3 -lnl-nf-3`

in Ubuntu 15 this program will compile, but will not work with message

```
nl_cache_mngr_add: Unknown or invalid cache type
```

But, it works when using clang !! what the hell ?! the evil in `--as-needed` used in Ubuntu's gcc by default. Since gcc do not knows that `libnl-nf-3` uses `__init` function, it is eliminated from list of libraries to link.

So, if I add `-Wl,--no-as-needed`, everything works as expected.

So will you add some fix against that? maybe make this flag to appear in `$(shell pkg-config --libs libnl-xxxx )` ?

Here is a minimal program:
```
#include <netlink/netfilter/nfnl.h>
#include <netlink/netfilter/ct.h>

static void change_cb (struct nl_cache *cache, struct nl_object *obj, int action, void *data) {}

int main (void)
{
  struct nl_sock *sock;
  struct nl_cache_mngr *mngr;
  struct nl_cache *ct_cache;
  int err;
  if ((sock = nl_socket_alloc ()) == NULL)
    return 1;
  if ((err = nl_cache_mngr_alloc (sock, NETLINK_NETFILTER, NL_AUTO_PROVIDE, &mngr)) < 0)
  {
    nl_perror (err, "err=nl_cache_mngr_alloc");
    return 2;
  }
  if ((err = nl_cache_mngr_add (mngr, "netfilter/ct", &change_cb, NULL, &ct_cache)) < 0)
  {
    nl_perror (err, "nl_cache_mngr_add");
    return 3;
  }
  return 0;
}
```

**Comment by socketpair** [comment]
Just for history:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68902

**Comment by lkundrak** [comment]
Thanks for the report, but there's not much we can do about it. We can't add a -Wl,--no-as-needed to our pkg-config file since we could disable --as-needed for legitimate use cases and we can't bound it with --push-state and --pop-state, since they don't work with gold.

Ideally, your distribution should fix their toolchain and don't silently drop libraries.

Other possible workarounds are adding --no-as-needed to your Makefile or using some symbol from the libnm-nf-3 library so that the DT_NEEDED won't get evicted.

**Comment by thom311** [comment]
I agree with Lubomir.

Doesn't seem right to do upstream because we don't know which options a potential user wants. Please add the linker option to your own Makefile where you link with libnl.

**Comment by socketpair** [comment]
Reported bug against linker: https://sourceware.org/bugzilla/show_bug.cgi?id=19372
